server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      file-size-threshold: 2KB
      max-request-size: 6MB
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/yantra_db
    username: postgres
    password: softwarica
    driver-class-name: org.postgresql.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
# print both sql statement and query result to console
# log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*.xml
